services:
    tavy315_sylius_product_subscriptions.repository.subscription:
        class: Tavy315\SyliusProductSubscriptionsPlugin\Repository\SubscriptionRepository
        autowire: true
        autoconfigure: true

    Tavy315\SyliusProductSubscriptionsPlugin\Repository\SubscriptionRepositoryInterface:
        alias: tavy315_sylius_product_subscriptions.repository.subscription

    Tavy315\SyliusProductSubscriptionsPlugin\Command\SendNotificationsCommand:
        tags: [ 'console.command' ]
        arguments:
            - '@sylius.availability_checker'
            - '@Tavy315\SyliusProductSubscriptionsPlugin\Service\SubscriptionNotifierInterface'
            - '@tavy315_sylius_product_subscriptions.repository.subscription'

    tavy315_sylius_product_subscriptions.custom_factory.subscription:
        class: Tavy315\SyliusProductSubscriptionsPlugin\Factory\SubscriptionFactory
        decorates: tavy315_sylius_product_subscriptions.factory.subscription
        public: false
        arguments:
            - "@tavy315_sylius_product_subscriptions.custom_factory.subscription.inner"

    Tavy315\SyliusProductSubscriptionsPlugin\EventSubscriber\NotifierSubscriber:
        arguments:
            - '@sylius.availability_checker'
            - '@Tavy315\SyliusProductSubscriptionsPlugin\Service\SubscriptionNotifierInterface'
            - '@tavy315_sylius_product_subscriptions.repository.subscription'
        tags:
            - { name: kernel.event_listener, event: sylius.product_variant.post_update, method: productVariantNotification }
            - { name: kernel.event_listener, event: sylius.product.post_update, method: productNotification }

    Tavy315\SyliusProductSubscriptionsPlugin\Service\SubscriptionNotifierInterface:
        class: Tavy315\SyliusProductSubscriptionsPlugin\Service\SubscriptionNotifier
        arguments:
            - '@sylius.email_sender'

    Tavy315\SyliusProductSubscriptionsPlugin\Controller\AddSubscriptionAction:
        tags: [ 'controller.service_arguments' ]
        arguments:
            - '@sylius.availability_checker'
            - '@sylius.context.channel'
            - '@sylius.context.customer'
            - '@sylius.repository.customer'
            - '@sylius.factory.customer'
            - '@tavy315_sylius_product_subscriptions.factory.subscription'
            - '@form.factory'
            - '@sylius.context.locale'
            - '@sylius.repository.product'
            - '@tavy315_sylius_product_subscriptions.repository.subscription'
            - '@translator'
            - '@twig'
            - '@validator'

    Tavy315\SyliusProductSubscriptionsPlugin\Controller\DeleteSubscriptionAction:
        tags: [ 'controller.service_arguments' ]
        arguments:
            - '@sylius.context.customer'
            - '@sylius.repository.product'
            - '@router'
            - '@request_stack'
            - '@tavy315_sylius_product_subscriptions.repository.subscription'
            - '@translator'

    Tavy315\SyliusProductSubscriptionsPlugin\Controller\SubscriptionFormAction:
        tags: [ 'controller.service_arguments' ]
        arguments:
            - '@sylius.context.customer'
            - '@form.factory'
            - '@twig'

    Tavy315\SyliusProductSubscriptionsPlugin\Menu\AccountMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addMenuItems }

    Tavy315\SyliusProductSubscriptionsPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
